// <auto-generated />
using System;
using CildAdoptie.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CildAdoptie.Migrations
{
    [DbContext(typeof(AdoptionDbContext))]
    partial class AdoptionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CildAdoptie.Models.AdoptionRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApplicantName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContactInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AdoptionRequests");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7ffa16b3-51ed-4e80-97b6-08dd1f8677e6"),
                            ApplicantName = "John Doe",
                            ChildId = new Guid("7ffa16b3-51ed-4e80-97b6-08dd1f8677e1"),
                            ContactInfo = "johndoe@example.com"
                        },
                        new
                        {
                            Id = new Guid("7ffa16b3-51ed-4e80-97b6-08dd1f8677e7"),
                            ApplicantName = "Jane Smith",
                            ChildId = new Guid("7ffa16b3-51ed-4e80-97b6-08dd1f8677e2"),
                            ContactInfo = "janesmith@example.com"
                        },
                        new
                        {
                            Id = new Guid("7ffa16b3-51ed-4e80-97b6-08dd1f8677e8"),
                            ApplicantName = "Michael Brown",
                            ChildId = new Guid("7ffa16b3-51ed-4e80-97b6-08dd1f8677e3"),
                            ContactInfo = "michaelbrown@example.com"
                        });
                });

            modelBuilder.Entity("CildAdoptie.Models.Child", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Children");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7ffa16b3-51ed-4e80-97b6-08dd1f8677e1"),
                            Age = 4,
                            Description = "Loves painting and playing outdoors.",
                            Gender = "Female",
                            Name = "Anna"
                        },
                        new
                        {
                            Id = new Guid("7ffa16b3-51ed-4e80-97b6-08dd1f8677e2"),
                            Age = 6,
                            Description = "Enjoys puzzles and building blocks.",
                            Gender = "Male",
                            Name = "Liam"
                        },
                        new
                        {
                            Id = new Guid("7ffa16b3-51ed-4e80-97b6-08dd1f8677e3"),
                            Age = 3,
                            Description = "Very curious and loves to read stories.",
                            Gender = "Female",
                            Name = "Sophia"
                        },
                        new
                        {
                            Id = new Guid("7ffa16b3-51ed-4e80-97b6-08dd1f8677e4"),
                            Age = 5,
                            Description = "Passionate about soccer and animals.",
                            Gender = "Male",
                            Name = "Noah"
                        },
                        new
                        {
                            Id = new Guid("7ffa16b3-51ed-4e80-97b6-08dd1f8677e5"),
                            Age = 7,
                            Description = "Loves music and dancing.",
                            Gender = "Female",
                            Name = "Emma"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
